"""added special_order

Revision ID: 03c60bde1b47
Revises: 5de83105611f
Create Date: 2019-03-17 12:05:49.496017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c60bde1b47'
down_revision = '5de83105611f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('special_order', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'special_order')
    # ### end Alembic commands ###
