"""added 'category' to Personnel table

Revision ID: 3e5bd81829b1
Revises: 75399621fbae
Create Date: 2019-02-24 16:08:07.139852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5bd81829b1'
down_revision = '75399621fbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personnel', sa.Column('category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personnel', 'category')
    # ### end Alembic commands ###
