"""added description to Parts model

Revision ID: 42da3db3904d
Revises: 7f23b191f807
Create Date: 2019-03-17 10:54:19.181109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42da3db3904d'
down_revision = '7f23b191f807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'description')
    # ### end Alembic commands ###
