"""added vin

Revision ID: 5de83105611f
Revises: 42da3db3904d
Create Date: 2019-03-17 11:35:40.669923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de83105611f'
down_revision = '42da3db3904d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vin')
    # ### end Alembic commands ###
