"""initial migration

Revision ID: 75399621fbae
Revises: 
Create Date: 2019-02-19 16:30:50.733798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75399621fbae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('manifests',
    sa.Column('manifest_id', sa.Integer(), nullable=False),
    sa.Column('shipping_handling', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('manifest_id')
    )
    op.create_table('parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('personnel',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_i', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('purchaseorders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('shipping_handling', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('vehicle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['personnel.employee_id'], ),
    sa.ForeignKeyConstraint(['vehicle'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_table('maintenance',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_table('manifest_items',
    sa.Column('manifest_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['manifest_id'], ['manifests.manifest_id'], ),
    sa.PrimaryKeyConstraint('manifest_id', 'item_id')
    )
    op.create_table('po_items',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchaseorders.po_id'], ),
    sa.PrimaryKeyConstraint('po_id', 'item_id')
    )
    op.create_table('shipments',
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('arrival_status', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.Float(), nullable=True),
    sa.Column('depart_time', sa.DateTime(), nullable=True),
    sa.Column('est_time_arrival', sa.DateTime(), nullable=True),
    sa.Column('confirmation', sa.Boolean(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('manifest_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manifest_id'], ['manifests.manifest_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchaseorders.po_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('ship_id')
    )
    op.create_table('vehicle_parts',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'part_id')
    )
    op.create_table('maintenance_parts',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.maintenance_id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.part_id'], ),
    sa.PrimaryKeyConstraint('maintenance_id', 'part_id')
    )
    op.create_table('shipment_drivers',
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['shipments.ship_id'], ),
    sa.PrimaryKeyConstraint('ship_id', 'driver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_drivers')
    op.drop_table('maintenance_parts')
    op.drop_table('vehicle_parts')
    op.drop_table('shipments')
    op.drop_table('po_items')
    op.drop_table('manifest_items')
    op.drop_table('maintenance')
    op.drop_table('drivers')
    op.drop_table('vehicles')
    op.drop_table('purchaseorders')
    op.drop_table('personnel')
    op.drop_table('parts')
    op.drop_table('manifests')
    op.drop_table('items')
    # ### end Alembic commands ###
