"""added shipment_personnel relation

Revision ID: 7f23b191f807
Revises: be3a2b8b035c
Create Date: 2019-03-16 18:25:41.063169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f23b191f807'
down_revision = 'be3a2b8b035c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_personnel',
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['personnel.employee_id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['shipments.ship_id'], ),
    sa.PrimaryKeyConstraint('ship_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_personnel')
    # ### end Alembic commands ###
