"""added more shipment fields

Revision ID: be3a2b8b035c
Revises: 3e5bd81829b1
Create Date: 2019-03-06 18:14:14.309720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3a2b8b035c'
down_revision = '3e5bd81829b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('destination_address', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('destination_company', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('shipment_type', sa.Boolean(), nullable=True))
    op.add_column('shipments', sa.Column('source_address', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('source_company', sa.String(), nullable=True))
    #op.drop_column('shipments', 'confirmation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('shipments', sa.Column('confirmation', sa.BOOLEAN(), nullable=True))
    op.drop_column('shipments', 'source_company')
    op.drop_column('shipments', 'source_address')
    op.drop_column('shipments', 'shipment_type')
    op.drop_column('shipments', 'destination_company')
    op.drop_column('shipments', 'destination_address')
    # ### end Alembic commands ###
